import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigrations1707145760266 implements MigrationInterface {
    public readonly name = 'AutoGeneratedMigrations1707145760266'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "Task" ("id" SERIAL NOT NULL, "cost" numeric NOT NULL, "startTime" TIMESTAMP, "endTime" TIMESTAMP, CONSTRAINT "PK_95d9364b8115119ba8b15a43592" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Job" ("id" SERIAL NOT NULL, "startTime" TIMESTAMP, "endTime" TIMESTAMP, "taskId" integer, "userId" integer, CONSTRAINT "PK_981d90e7185b9ec1ee6b814ec21" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "User" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "rate" numeric NOT NULL, CONSTRAINT "PK_9862f679340fb2388436a5ab3e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "Job" ADD CONSTRAINT "FK_70f0ff2bfc80caf3da1ca142367" FOREIGN KEY ("taskId") REFERENCES "Task"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Job" ADD CONSTRAINT "FK_f6072b818d59e18ec417807f484" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {}

}
